//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input Mappers/Pilot.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Pilot : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Pilot()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Pilot"",
    ""maps"": [
        {
            ""name"": ""Center"",
            ""id"": ""522bbbee-0a19-456e-8380-93d05d5a3480"",
            ""actions"": [
                {
                    ""name"": ""ZoomIn"",
                    ""type"": ""Button"",
                    ""id"": ""6fe34a9b-6050-47f4-977a-5eac80b989f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a75ddee9-1b9f-41f9-bc3e-d138900f16dc"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomIn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Manual"",
            ""id"": ""ceef3b21-ae67-4999-853f-dbfc8369997b"",
            ""actions"": [
                {
                    ""name"": ""SwapPage"",
                    ""type"": ""Value"",
                    ""id"": ""9aa01093-b879-407d-8951-0d4be3dbde63"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Bookmark"",
                    ""type"": ""Value"",
                    ""id"": ""ab8db3bc-1671-4454-b858-8babe00c5192"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MonitorScroll"",
                    ""type"": ""Value"",
                    ""id"": ""d2de391e-d4ff-42e2-beb7-0b017add309d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Direction"",
                    ""id"": ""f487f00b-2313-430a-ab9d-c7fed3a17e72"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bookmark"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9772a39f-4e27-4351-aa95-59761305a64a"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bookmark"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1082569f-792d-42d0-9dc4-b0c4af8978ce"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bookmark"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ea5ca1f7-ff1c-45e8-bc0a-62080ef2505a"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bookmark"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b2dcc638-5ece-4d4e-85ac-89b255c0e615"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bookmark"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""7e820f15-2652-4720-996f-a673a3d03527"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapPage"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""12f2e60a-8bef-494b-86f3-7604050b6bc4"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapPage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""1cb8090d-be44-4084-982e-35e5e9209ee2"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapPage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""de5339ec-a929-4d2d-b610-f53ec1f53947"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MonitorScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Cockpit"",
            ""id"": ""ad7c2db4-f878-45c6-a2d0-6a0b24d17699"",
            ""actions"": [
                {
                    ""name"": ""MoveCamera"",
                    ""type"": ""Value"",
                    ""id"": ""b9faac5f-fb54-4d92-bb7a-23593badfda5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ToManualScreen"",
                    ""type"": ""Button"",
                    ""id"": ""0b26c865-150c-48fd-8d7a-5ae12e979854"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToCockpitScreen"",
                    ""type"": ""Button"",
                    ""id"": ""98cf18c8-b71c-46d0-8638-4eedb8cb0d6b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5d31f5c9-6eee-4551-9e35-18998626eb98"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e53c4d37-b710-4133-8090-fc147a1a97f5"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToCockpitScreen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""442ee1b9-902e-440f-a504-70eb64c60a42"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToManualScreen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Shooting"",
            ""id"": ""c1cf1589-51ce-451f-8985-1d177881d7d8"",
            ""actions"": [
                {
                    ""name"": ""ShootingMovement"",
                    ""type"": ""Value"",
                    ""id"": ""7c0bf33b-32ca-4388-97a0-74a86acb3b96"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shooting"",
                    ""type"": ""Button"",
                    ""id"": ""97d8108c-27a2-4053-b700-523e65bfa22c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7ee91439-4028-4132-bd3b-68743d4473c0"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootingMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d62c6b42-bd54-4f9a-9136-1944d3f2788a"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shooting"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Center
        m_Center = asset.FindActionMap("Center", throwIfNotFound: true);
        m_Center_ZoomIn = m_Center.FindAction("ZoomIn", throwIfNotFound: true);
        // Manual
        m_Manual = asset.FindActionMap("Manual", throwIfNotFound: true);
        m_Manual_SwapPage = m_Manual.FindAction("SwapPage", throwIfNotFound: true);
        m_Manual_Bookmark = m_Manual.FindAction("Bookmark", throwIfNotFound: true);
        m_Manual_MonitorScroll = m_Manual.FindAction("MonitorScroll", throwIfNotFound: true);
        // Cockpit
        m_Cockpit = asset.FindActionMap("Cockpit", throwIfNotFound: true);
        m_Cockpit_MoveCamera = m_Cockpit.FindAction("MoveCamera", throwIfNotFound: true);
        m_Cockpit_ToManualScreen = m_Cockpit.FindAction("ToManualScreen", throwIfNotFound: true);
        m_Cockpit_ToCockpitScreen = m_Cockpit.FindAction("ToCockpitScreen", throwIfNotFound: true);
        // Shooting
        m_Shooting = asset.FindActionMap("Shooting", throwIfNotFound: true);
        m_Shooting_ShootingMovement = m_Shooting.FindAction("ShootingMovement", throwIfNotFound: true);
        m_Shooting_Shooting = m_Shooting.FindAction("Shooting", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Center
    private readonly InputActionMap m_Center;
    private ICenterActions m_CenterActionsCallbackInterface;
    private readonly InputAction m_Center_ZoomIn;
    public struct CenterActions
    {
        private @Pilot m_Wrapper;
        public CenterActions(@Pilot wrapper) { m_Wrapper = wrapper; }
        public InputAction @ZoomIn => m_Wrapper.m_Center_ZoomIn;
        public InputActionMap Get() { return m_Wrapper.m_Center; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CenterActions set) { return set.Get(); }
        public void SetCallbacks(ICenterActions instance)
        {
            if (m_Wrapper.m_CenterActionsCallbackInterface != null)
            {
                @ZoomIn.started -= m_Wrapper.m_CenterActionsCallbackInterface.OnZoomIn;
                @ZoomIn.performed -= m_Wrapper.m_CenterActionsCallbackInterface.OnZoomIn;
                @ZoomIn.canceled -= m_Wrapper.m_CenterActionsCallbackInterface.OnZoomIn;
            }
            m_Wrapper.m_CenterActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ZoomIn.started += instance.OnZoomIn;
                @ZoomIn.performed += instance.OnZoomIn;
                @ZoomIn.canceled += instance.OnZoomIn;
            }
        }
    }
    public CenterActions @Center => new CenterActions(this);

    // Manual
    private readonly InputActionMap m_Manual;
    private IManualActions m_ManualActionsCallbackInterface;
    private readonly InputAction m_Manual_SwapPage;
    private readonly InputAction m_Manual_Bookmark;
    private readonly InputAction m_Manual_MonitorScroll;
    public struct ManualActions
    {
        private @Pilot m_Wrapper;
        public ManualActions(@Pilot wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwapPage => m_Wrapper.m_Manual_SwapPage;
        public InputAction @Bookmark => m_Wrapper.m_Manual_Bookmark;
        public InputAction @MonitorScroll => m_Wrapper.m_Manual_MonitorScroll;
        public InputActionMap Get() { return m_Wrapper.m_Manual; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ManualActions set) { return set.Get(); }
        public void SetCallbacks(IManualActions instance)
        {
            if (m_Wrapper.m_ManualActionsCallbackInterface != null)
            {
                @SwapPage.started -= m_Wrapper.m_ManualActionsCallbackInterface.OnSwapPage;
                @SwapPage.performed -= m_Wrapper.m_ManualActionsCallbackInterface.OnSwapPage;
                @SwapPage.canceled -= m_Wrapper.m_ManualActionsCallbackInterface.OnSwapPage;
                @Bookmark.started -= m_Wrapper.m_ManualActionsCallbackInterface.OnBookmark;
                @Bookmark.performed -= m_Wrapper.m_ManualActionsCallbackInterface.OnBookmark;
                @Bookmark.canceled -= m_Wrapper.m_ManualActionsCallbackInterface.OnBookmark;
                @MonitorScroll.started -= m_Wrapper.m_ManualActionsCallbackInterface.OnMonitorScroll;
                @MonitorScroll.performed -= m_Wrapper.m_ManualActionsCallbackInterface.OnMonitorScroll;
                @MonitorScroll.canceled -= m_Wrapper.m_ManualActionsCallbackInterface.OnMonitorScroll;
            }
            m_Wrapper.m_ManualActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SwapPage.started += instance.OnSwapPage;
                @SwapPage.performed += instance.OnSwapPage;
                @SwapPage.canceled += instance.OnSwapPage;
                @Bookmark.started += instance.OnBookmark;
                @Bookmark.performed += instance.OnBookmark;
                @Bookmark.canceled += instance.OnBookmark;
                @MonitorScroll.started += instance.OnMonitorScroll;
                @MonitorScroll.performed += instance.OnMonitorScroll;
                @MonitorScroll.canceled += instance.OnMonitorScroll;
            }
        }
    }
    public ManualActions @Manual => new ManualActions(this);

    // Cockpit
    private readonly InputActionMap m_Cockpit;
    private ICockpitActions m_CockpitActionsCallbackInterface;
    private readonly InputAction m_Cockpit_MoveCamera;
    private readonly InputAction m_Cockpit_ToManualScreen;
    private readonly InputAction m_Cockpit_ToCockpitScreen;
    public struct CockpitActions
    {
        private @Pilot m_Wrapper;
        public CockpitActions(@Pilot wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveCamera => m_Wrapper.m_Cockpit_MoveCamera;
        public InputAction @ToManualScreen => m_Wrapper.m_Cockpit_ToManualScreen;
        public InputAction @ToCockpitScreen => m_Wrapper.m_Cockpit_ToCockpitScreen;
        public InputActionMap Get() { return m_Wrapper.m_Cockpit; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CockpitActions set) { return set.Get(); }
        public void SetCallbacks(ICockpitActions instance)
        {
            if (m_Wrapper.m_CockpitActionsCallbackInterface != null)
            {
                @MoveCamera.started -= m_Wrapper.m_CockpitActionsCallbackInterface.OnMoveCamera;
                @MoveCamera.performed -= m_Wrapper.m_CockpitActionsCallbackInterface.OnMoveCamera;
                @MoveCamera.canceled -= m_Wrapper.m_CockpitActionsCallbackInterface.OnMoveCamera;
                @ToManualScreen.started -= m_Wrapper.m_CockpitActionsCallbackInterface.OnToManualScreen;
                @ToManualScreen.performed -= m_Wrapper.m_CockpitActionsCallbackInterface.OnToManualScreen;
                @ToManualScreen.canceled -= m_Wrapper.m_CockpitActionsCallbackInterface.OnToManualScreen;
                @ToCockpitScreen.started -= m_Wrapper.m_CockpitActionsCallbackInterface.OnToCockpitScreen;
                @ToCockpitScreen.performed -= m_Wrapper.m_CockpitActionsCallbackInterface.OnToCockpitScreen;
                @ToCockpitScreen.canceled -= m_Wrapper.m_CockpitActionsCallbackInterface.OnToCockpitScreen;
            }
            m_Wrapper.m_CockpitActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveCamera.started += instance.OnMoveCamera;
                @MoveCamera.performed += instance.OnMoveCamera;
                @MoveCamera.canceled += instance.OnMoveCamera;
                @ToManualScreen.started += instance.OnToManualScreen;
                @ToManualScreen.performed += instance.OnToManualScreen;
                @ToManualScreen.canceled += instance.OnToManualScreen;
                @ToCockpitScreen.started += instance.OnToCockpitScreen;
                @ToCockpitScreen.performed += instance.OnToCockpitScreen;
                @ToCockpitScreen.canceled += instance.OnToCockpitScreen;
            }
        }
    }
    public CockpitActions @Cockpit => new CockpitActions(this);

    // Shooting
    private readonly InputActionMap m_Shooting;
    private IShootingActions m_ShootingActionsCallbackInterface;
    private readonly InputAction m_Shooting_ShootingMovement;
    private readonly InputAction m_Shooting_Shooting;
    public struct ShootingActions
    {
        private @Pilot m_Wrapper;
        public ShootingActions(@Pilot wrapper) { m_Wrapper = wrapper; }
        public InputAction @ShootingMovement => m_Wrapper.m_Shooting_ShootingMovement;
        public InputAction @Shooting => m_Wrapper.m_Shooting_Shooting;
        public InputActionMap Get() { return m_Wrapper.m_Shooting; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ShootingActions set) { return set.Get(); }
        public void SetCallbacks(IShootingActions instance)
        {
            if (m_Wrapper.m_ShootingActionsCallbackInterface != null)
            {
                @ShootingMovement.started -= m_Wrapper.m_ShootingActionsCallbackInterface.OnShootingMovement;
                @ShootingMovement.performed -= m_Wrapper.m_ShootingActionsCallbackInterface.OnShootingMovement;
                @ShootingMovement.canceled -= m_Wrapper.m_ShootingActionsCallbackInterface.OnShootingMovement;
                @Shooting.started -= m_Wrapper.m_ShootingActionsCallbackInterface.OnShooting;
                @Shooting.performed -= m_Wrapper.m_ShootingActionsCallbackInterface.OnShooting;
                @Shooting.canceled -= m_Wrapper.m_ShootingActionsCallbackInterface.OnShooting;
            }
            m_Wrapper.m_ShootingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ShootingMovement.started += instance.OnShootingMovement;
                @ShootingMovement.performed += instance.OnShootingMovement;
                @ShootingMovement.canceled += instance.OnShootingMovement;
                @Shooting.started += instance.OnShooting;
                @Shooting.performed += instance.OnShooting;
                @Shooting.canceled += instance.OnShooting;
            }
        }
    }
    public ShootingActions @Shooting => new ShootingActions(this);
    public interface ICenterActions
    {
        void OnZoomIn(InputAction.CallbackContext context);
    }
    public interface IManualActions
    {
        void OnSwapPage(InputAction.CallbackContext context);
        void OnBookmark(InputAction.CallbackContext context);
        void OnMonitorScroll(InputAction.CallbackContext context);
    }
    public interface ICockpitActions
    {
        void OnMoveCamera(InputAction.CallbackContext context);
        void OnToManualScreen(InputAction.CallbackContext context);
        void OnToCockpitScreen(InputAction.CallbackContext context);
    }
    public interface IShootingActions
    {
        void OnShootingMovement(InputAction.CallbackContext context);
        void OnShooting(InputAction.CallbackContext context);
    }
}
